export { default as Contacts } from "./contacts/Contacts";
export { default as Intro } from "./intro/Intro";
export { default as Portfolio } from "./portfolio/Portfolio";
export { default as Testimonials } from "./testimonials/Testimonials";
export { default as TopBar } from "./topbar/TopBar";
export { default as Works } from "./works/Works";
export { default as Menu } from "./menu/Menu";
export { default as PortfolioCatItems } from "./portfolioCats/PortfolioCats";
export { default as Footer } from "./footer/Footer";
